### ISSUE TITLE
aws_iam_policy_attachment bug

### ISSUE THREAD

**Issue by denzalman** [wata727/tf_aws_ecs_on_spotfleet#5]
`resource "aws_iam_policy_attachment" "ecs_service" {
  name       = "${var.app_name}-ecs-service"
  roles        = ["${aws_iam_role.ecs_service.name}"]
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole"
}
`

This code erases all roles connected to the policy because **aws_iam_policy_attachment** resource creates exclusive attachments of IAM policies. Across the entire AWS account,  all of the users/roles/groups to which a single policy is attached must be declared by a single aws_iam_policy_attachment resource. 

fix:

resource "aws_iam_role_policy_attachment" "ecs_service" {
  name       = "${var.app_name}-ecs-service"
  role        = "${aws_iam_role.ecs_service.id}"
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole"
}

**Comment by wata727** [comment]
Fixed by https://github.com/wata727/tf_aws_ecs_on_spotfleet/pull/6
